### ISSUE TITLE
Hipchat API v2

### ISSUE THREAD

**Issue by davout1806** [kulttuuri/hipchat_mediawiki#10]
Pardon my ignorance if this is incorrect but it appears this project is using version 1 of Hipchat API. If true, any plans to update to version 2?

Thanks.

**Comment by kulttuuri** [comment]
Good idea! I'll take a look at API v2 once I'm back home beginning next month to see if I can roll in the update.

If no problems arise with API update, I will probably add new configuration parameter for setting API version which would default to 2 but if someone still wants to use V1, he could.

**Comment by kulttuuri** [comment]
Implemented! Check this commit for more information: https://github.com/kulttuuri/hipchat_mediawiki/commit/15f758df8e0bbe082303726f368a66e6b648a392
